### ISSUE TITLE
Review NOI

### ISSUE THREAD

**Issue by smiths** [smiths/TCTvMDE#1]
@richpaige, the NOI (https://github.com/smiths/TCTvMDE/blob/master/NOI.txt) is ready for your review.  It isn't very good, but it is a starting point.  It is already almost 2500 characters, so what is there shows how short 2500 characters really is!  I think we could get some space back by taking out the sub-headings.  There is also some repetition, because I added sections for novelty and expected significance.  We probably do not have to make those explicit in the final draft, but I think they are good for discussion right now.

I added in the idea of an assurance case under the research methodology.  I'm certainly open to other ideas under methodology.  I just wanted to have something specific to discuss.

**Comment by JacquesCarette** [comment]
Richard first, then me?

**Comment by smiths** [comment]
Yes.  :-)

**Comment by richpaige** [comment]
I've just pushed some revisions to the NOI (and hopefully have resolved the merge conflicts).

**Comment by smiths** [comment]
Thank you @richpaige.  Your changes look good to me.  Please feel free to continue to make changes, or to suggest more major shifts in focus or presentation.  @JacquesCarette, the timing seems good now for you to have a look over the NOI.  We can create a separate issue if you would like, or just keep the discussion under this issue.  @ZMotamed is planning on reviewing the NOI tomorrow (Thursday, July 25).

**Comment by JacquesCarette** [comment]
Done.  Changes pushed.

**Comment by ZMotamed** [comment]
Done.

**Comment by smiths** [comment]
Thank you all for your feedback.  I have revised your revisions of the NOI in 9611338.  I needed to make the number of characters less and that included removing the hard-returns that helped track changes.  I do not believe that I changed the meaning of what you wrote, but if you notice something, please let me know.

The application is complete, except for the following:

- I need to switch @ZMotamed from co-applicant to co-principal investigator
- Javier needs to accept the invitation
- the suggested reviewers need to be added (From #5 and #4)
- research services needs to review (I have sent the current draft to Nathan)

**Comment by smiths** [comment]
I have resent the invitation to Javier (July 27).

**Comment by smiths** [comment]
Javier accepted the invitation.  The NOI was successfully completed.  Now working on the LOI.
