### ISSUE TITLE
Fields of Research

### ISSUE THREAD

**Issue by smiths** [smiths/TCTvMDE#2]
Please let me know if you think additional fields of research should be added to the NOI.  We cannot change these once the NOI is submitted.  So far I have the following primary fields of research:

- RDF1020305 Computer and information sciences, Programming languages and software engineering Software system models
- RDF1039903 Physical sciences, Other physical sciences Medical physics
- RDF3020101 Clinical medicine Cardiorespiratory medicine and hematology, Cardiology and circulatory sciences (including cardiovascular disease)

The research development classification can be found at:

http://www.sshrc-crsh.gc.ca/funding-financement/nfrf-fnfr/CRDC_Web_EF.xlsx

If you would rather not look through the list, but there are some research fields you expect to see.  You can give me your version of the name, and I'll find the closest match in the government's list.

In particular, @ZMotamed, do you think there should be a mechanical engineering field represented, or medical imaging, or something else?

**Comment by JacquesCarette** [comment]
We should consider
- RDF1020106 - Knowledge representation
- RDF1020207 - Mathematical software
- RDF1020305 - Software system models
- RDF1020802 - Computational biomodelling

**Comment by smiths** [comment]
Great!  Thank you @JacquesCarette.  I used all of your suggestions, except for computational biomodelling.  I would have included it too, but it turns out the that application only allows for 5 research fields at most.

**Comment by smiths** [comment]
I'll close this issue.  If anyone would like to change the choices, we can reopen and discuss.
