### ISSUE TITLE
Model Driven Engineering Reviewers

### ISSUE THREAD

**Issue by smiths** [smiths/TCTvMDE#4]
@richpaige can you give me the names of 2 to 3 appropriate reviewers for the new research fund.  My guess is that you would look for MDE experts.

**Comment by smiths** [comment]
@JacquesCarette, if you have names to suggest, I'd be happy to incorporate them as well.

**Comment by richpaige** [comment]
Canadian reviewers:
- Lionel Briand, University of Ottawa
- Sebastian Mosser, Universite du Quebec a Montreal
International reviewers:
- Jeff Gray, University of Alabama at Birmingham
- Steffen Zschaler, Kings College London, UK
- Andy Schurr, Darmstadt University, Germany
- Massimo Tisi, University of Nantes, France

**Comment by smiths** [comment]
That was fast!  Thank you @richpaige.  😄

**Comment by JacquesCarette** [comment]
I would also add
- Jeremy Gibbons, University of Oxford
to the list.  And maybe also 
- Eelco Visser

**Comment by smiths** [comment]
Sounds good.  Thank you @JacquesCarette.
