### ISSUE TITLE
Medical Physics Experts

### ISSUE THREAD

**Issue by smiths** [smiths/TCTvMDE#5]
@ZMotamed can you give me the names of 2 to 3 medical physics experts that could review our proposal.  Would you like to provide names of clinicians too, or should we ask Javier for recommendations?

**Comment by ZMotamed** [comment]
Hadi Mohammadi
https://engineering.ok.ubc.ca/about/contact/hadi-mohammadi/

Jonathon Leipsic
https://www.hli.ubc.ca/profile/leipsic/jonathon

David A. Steinman
https://www.mie.utoronto.ca/mie/faculty/steinman

You can ask more from Javier if you prefer.

**Comment by smiths** [comment]
I don't think there is a need to ask Javier.  I'll enter these names into the application.  Thank you!
